project_id = "study-line"

[db]
port = 54322
major_version = 16

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]

[storage]
enabled = true
