-- Phase 14 (Notifications) delivery plumbing.
--
-- Notification rows are generated by a scheduled job (see
-- src/actions/notifications.jobs.ts, triggered by /api/cron/notifications),
-- which re-runs hourly over the same source data. `dedupe_key` is what keeps
-- that idempotent: the job upserts on (user_id, dedupe_key) and ignores
-- duplicates, so a lesson scheduled for tomorrow produces exactly one
-- notification no matter how many times the job runs before then.
alter table public.notifications
  add column dedupe_key text,
  add column emailed_at timestamptz;

comment on column public.notifications.dedupe_key is
  'Stable per-(user, subject, occurrence) key, e.g. homework_due:<homework_id>:<deadline>. '
  'Null is allowed so a one-off notification can skip deduplication entirely.';

comment on column public.notifications.emailed_at is
  'Set once the notification has been emailed, so the job never sends twice.';

-- Partial so that dedupe_key IS NULL rows (one-offs) do not collide with each
-- other — in Postgres, nulls are distinct in a unique index anyway, but the
-- predicate keeps the index small and its intent explicit.
create unique index idx_notifications_dedupe
  on public.notifications (user_id, dedupe_key)
  where dedupe_key is not null;

-- Drives "email me my notifications too", alongside the existing
-- enabledInBrowser flag. See NotificationPreferences in src/lib/types/settings.ts.
alter table public.settings
  alter column notification_preferences set default '{
    "enabledInBrowser": true,
    "enabledInEmail": false,
    "types": {
      "upcoming_lesson": true,
      "homework_due": true,
      "daily_reminder": true,
      "review_reminder": true
    }
  }'::jsonb;

-- Backfill rows provisioned before this migration; `||` leaves any existing
-- explicit value alone only if we put it on the left, so guard on absence.
update public.settings
set notification_preferences =
  notification_preferences || '{"enabledInEmail": false}'::jsonb
where not (notification_preferences ? 'enabledInEmail');
